name: CD

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  artifact:
    strategy:
      fail-fast: false
      matrix:
        include:
          - type: windows-x64
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - type: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    name: Publish Artifact (${{ matrix.type }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        shell: bash
        run: |
          cargo build --verbose --locked --release

      - name: Post-build
        id: postbuild
        shell: bash
        run: |
          name="dxm-${{ matrix.type }}"

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            name="$name.exe"
            mv "./target/release/dxm.exe" "./$name"
          else
            mv "./target/release/dxm" "./$name"
          fi

          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.postbuild.outputs.name }}
          path: ./${{ steps.postbuild.outputs.name }}

  release:
    name: Draft Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download archives
        uses: actions/download-artifact@v6

      - name: Archive
        shell: bash
        run: |
          version="${{ github.ref_name }}"

          mv -vfT "dxm-windows-x64.exe/dxm-windows-x64.exe" "dxm.exe"
          zip "dxm-$version-windows-x64.zip" "dxm.exe"

          mv -vfT "dxm-linux-x64/dxm-linux-x64" "dxm"
          tar -czvf "dxm-$version-linux-x64.tar.gz" "dxm"

      - name: Draft release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            ./*.zip
            ./*.tar.gz

  crate:
    name: Publish Crate
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish crates
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
